로그인 기능 구현
Bob-Friend/bob-friend-iOS pull request #1
Opened 2021-08-30 02:25 UTC by skycat0212

@z-hoony
로그인 기능 구현되었습니다.
리뷰 부탁드립니다.

2021-08-30 03:29 UTC, z-hoony requested changes

2021-08-30 03:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Extension/CALayer+Border.swift
> +                break
switch 문에서 각 case에 대해 statement가 있을경우 break를 하지 않아도됩니다

2021-08-30 03:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    let baseUrl: String = Bundle.main.infoDictionary!["API_BASE_URL"] as! String
질문입니다. API_BASE_URL 을 환경변수로 지정했는데 테스트용 서버랑 배포용 서버가 분리되어있어서 이렇게 처리한건가요?

2021-08-30 03:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    }
`API` enum은 외부에서는 접근하지 않고 Network의 내부 메소드(`loginRequest(loginInfo:completion:)`같은)에서만 접근하는거같은데요. 각 내부 메소드에서 바로 "api/signin" 이라는 문자열을 쓰지않고 enum으로 분리한 이유가 있나요? 아니면 내부에서만 여러 메소드에서 하나의 case를 접근한다면 private 으로 타입을 지정하지 않은 이유가 있나요?

2021-08-30 03:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Protocols/LoginProtocol.swift
> +    func didSuccessLogin(_ notification: NSNotification) -> Void
swift에서는 `Notification`를 이용할 수 있는데 `NSNotification`을 이용하신 이유가 있나요?

2021-08-30 03:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewModel/LoginVM.swift
> +
VM -> V 로 이벤트 전달 방식을 Notification을 선택한 이유가 있나요? delegate 같은 다른 방식들을 놔두고요
그리고 VM은 V에 대해 알지 못해야할 것 같은데 생성자로 `UIViewController`을 받는 이유가 있나요? `Login` 프로토콜을 받아도 되지않을까요?
`LoginVM`은 왜 `Login` 프로토콜을 따르고있나요?

2021-08-30 03:36 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +    var loginVM: LoginVM?
LoginVM <-> LoginVC 사이에 순환 참조가 발생할것같아요

2021-08-30 03:37 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        loginVM = LoginVM(self)
`LoginVM`을 외부에서 넣어주지 않고 `viewDidLoad()`에서 직접 만드는 이유가 있을까요?

2021-08-30 03:40 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        setTxtFields()
`setUI()`가 `viewDidAppear(_:)`에서 호출이 되는데 그러면 다른 뷰컨트롤러에 의해서 가려졌다가 보일 때 마다 호출이 되면 최종적으로 `idTxtField.layer.addUnderBar()` 이런 코드들이 여러번 호출되서 `CALayer`가 계속 add 될 것 같은데 개선하면 좋을 것 같아요

2021-08-31 02:00 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    }
API의 URL 문자열을 직접 넣으면 API 명세가 바뀔 경우 변경사항을 반영하기 번거로울 수 있다고 생각해, 따로 모아두고자 하였습니다. 형식 지정자는 사용할 생각을 하지 못한 것 같습니다.

2021-08-31 02:07 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/Protocols/LoginProtocol.swift
> +    func didSuccessLogin(_ notification: NSNotification) -> Void
크게 의식하지 않고 사용한 것 같습니다. Swift에 적절하게 Notification으로 수정하겠습니다.

2021-08-31 02:12 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        loginVM = LoginVM(self)
"`LoginVM`을 외부에서 넣어주지 않고" 의 의미가 선언할 때 값을 할당하지 않은 이유에 대해서 말씀하신게 맞나요?
맞다면, 저는 `LoginVM` 에서 `LoginVC`를 참조하므로 `self`를 넣어주기 위해 `LoginVC` 객체가 만들어지고 난 이후인 `viewDidLoad()` 에서 직접 넣어주었습니다. 하지만 순환참조가 발생하는 문제로 다시 생각해봐야 할 것 같네요.

2021-08-31 02:19 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    let baseUrl: String = Bundle.main.infoDictionary!["API_BASE_URL"] as! String
넵. 배포용 서버는 테스트용 서버와 분리하여 개발될 예정입니다.
또, 테스트용, 배포용 서버에 관계없이 url 정보는 코드로 담기에 정보 노출의 위험이 있지 않을까하는 우려가 있어 환경변수를 사용해보았습니다.

2021-08-31 02:51 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/ViewModel/LoginVM.swift
> +
최근 publish-subscribe 패턴을 접하면서 Notification이 VM이 V를 알지 못하게 하면서도 정보 전달을 할 수 있는 편리한 방법이라고 생각하게 되어 사용하게 되었습니다. 혹시 이 코드의 경우 delegate를 사용하시는 것을 더 권장하시나요?

`Login`프로토콜을 받는 것은 미처 생각 못했습니다. 안 그래도 `UIViewController`를 받는 게 마음에 걸렸는데 감사합니다.

`LoginVM`은 컴파일을 막기 위해 `enrollObserver()`에서 셀렉터로 사용될 `didSuccessLogin`과 `didFailLogin`을  가지고 있어야 하고, 해당 메서드들이 실제로 사용될 `LoginVC`도 해당 메서드들을 구현해야 했습니다.  따라서 `LoginVM`과 `LoginVC` 사이의 같은 형태의 메서드가 필요하므로 `Login` 프로토콜을 만들어 양쪽 다 채택하게 해 주었습니다. 혹시 이러한 방식의 추상화가 적절하지 않나요?

2021-08-31 02:52 UTC, skycat0212 commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        setTxtFields()
넵 flag를 적용하여 최초 한 번만 적용되도록 하였습니다.

2021-08-31 13:21 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    let baseUrl: String = Bundle.main.infoDictionary!["API_BASE_URL"] as! String
url은 알고자하면 쉽게 알수있어서 위험한 정보가 아니라고 생각되네요 보안을 중요하게 여겨야 할 곳은 서버에서는 정상적인 사용자 뿐만 아니라 침입자도 접속 할 수 있다는 생각으로 개발을 해서 로그인 정보나 입력 값들을 철저히 검증하는게 좋아보여요

2021-08-31 13:24 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Model/Network.swift
> +    }
어차피 각 case가 한 곳에서만 쓰이니까 수정하는건 어떤 방식이든 한번만 수정하는게 똑같을 것 같긴한데 한곳에 모아두는게 편하게 찾을 수 있긴하겠네요

2021-08-31 13:25 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/Protocols/LoginProtocol.swift
> +    func didSuccessLogin(_ notification: NSNotification) -> Void
무조건 바꾸라는게 아니라 각 차이점을 알고 사용하시면됩니다~ 둘 차이가 있어요

2021-08-31 13:29 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewModel/LoginVM.swift
> +
Notification은 publish-subscribe 패턴으로 이용할 때 실수할 가능성이 있어서요 delegate 방식은 주는 곳과 받는 곳이 명확하지만 post 와 addObserver는 정해진 곳 외에서도 이용하게 될 수 있으니까요

2021-08-31 13:35 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        loginVM = LoginVM(self)
일단 `LoginVM`은 `LoginVC`를 몰라야하는데 `LoginVC` 내부에서 직접 만드는게 이상해보이지 않나요?
let loginVC = LoginVC()
loginVC.viewModel = LoginVM(loginVC)
LoginVC가 아닌 외부에서 이렇게 LoginVM을 만들어서 넣어주는게 좋아보여요
그리고 View : ViewModel = n : 1 관계라서 LoginVC에는 다른 뷰모델이 올 수 있는데 특정 뷰 모델을 지정하는건 이상해보여요

2021-08-31 13:56 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        loginVM = LoginVM(self)
그리고 `LoginVM`은 `LoginVC`을 몰라야 한다는 거에서 추가로 얘기를 하면 `LoginVM` 내부에서 `LoginVC`에 직접 옵저버를 추가해주는데 그렇게 되면 `LoginVM`은 `LoginVC`을 알 수 밖에 없습니다. 이걸 해결하려면 `LoginVC` 에서 뷰모델의 노티를 옵저브하게 수정하는 방법이 있습니다. 

```
protocol LoginViewModelProtocol {
    var loginNotification: Notification.Name { get }

    func login(id: String, password: String)
}

struct LoginVM: LoginViewModelProtocol {
    var loginNotification = Notification.Name("Login")

    func login(id: String, password: String) {
        Network.login(id, password) {
            NotificationCenter.default.post(name: loginNotification, object: 0)
        }
    }
}

class ViewController: UIViewController {
    func presentLogin() {
        let loginVC = LoginVC()
        loginVC.viewModel = LoginVM()

        present(loginVC, animated: true, completion: nil)
    }
}

class LoginVC: UIViewController {
    var viewModel: LoginViewModelProtocol!

    override func viewDidLoad() {
        super.viewDidLoad()

        NotificationCenter.default.addObserver(self, selector: #selector(result(_:)), name: viewModel.loginNotification, object: nil)
    }

    func login() {
        viewModel.login(id: "id", password: "pass")
    }

    @objc
    private func result(_ notification: Notification) {
        guard let result = notification.object as? Result<String, Error> else {
            return
        }

        switch result {
        case let .success(token):
            // 성공처리
            break
        case let .failure(error):
            // 실패처리
            break
        }
    }
}
```

예를 들면 이런 방법으로?!

2021-08-31 13:57 UTC, z-hoony commented on bob-friend-iOS/bob-friend-iOS/ViewController/LoginVC.swift
> +        setTxtFields()
flag를 적용해도 되지만 한번만 호출되는 `viewDidLoad()` 가 아닌 `viewDidAppear(_:)` 에서 호출하는 이유가 있나요?

2021-09-13 07:07 UTC, merged